extends: default

ignore: |
  node_modules/

rules:
  braces:
    forbid: non-empty
  comments:
    min-spaces-from-content: 1
  document-end: false
  document-start: false
  line-length:
    ignore: |
      .github/workflows/*
  indentation:
    spaces: 2
    indent-sequences: false
    check-multi-line-strings: true
  quoted-strings:
    quote-type: double
    required: only-when-needed
