name = 'paintbrush'
main = '.output/server/index.mjs'
account_id = 'ACCOUNT_ID'
compatibility_date = '2022-05-23'

[env.production]
routes = [ 'paintbrush.danifoldi.com/*' ]

[site]
bucket = '.output/public'

[build]
command = 'NITRO_PRESET=cloudflare npm run build'
