name: Approve and auto-merge dependabot PRs

permissions:
  pull-requests: write
  contents: write

on:
  pull_request:
    branches:
    - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
    - name: Fetch dependabot metadata
      id: metadata
      uses: dependabot/fetch-metadata@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Approve PR
      if: steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr checkout "${{ github.event.pull_request.html_url }}"
        if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
        then gh pr review --approve "${{ github.event.pull_request.html_url }}"
        else echo "PR already approved.";
        fi

    - name: Let Dependabot merge PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        gh pr comment --b "@dependabot merge" "${{ github.event.pull_request.html_url }}"
