name: Lint repository

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        npm ci

    - name: Run eslint
      if: always()
      run: |
        npm run lint:js

    - name: Run stylelint
      if: always()
      run: |
        npm run lint:css
